### PR TITLE
Update sw.po and add tuv.po

### PR DESCRIPTION
**Pull request by bkmgit**
Update Kiswahili translation

### CODE REVIEW

**Comment by perepujal** [comment]
Hi, I see a couple of fuzzy translations, is OK to submit them as fuzzy or do you want to finish them?
The strings are "Phrase Practice" and "This feature is not ready yet"
Thanks
Pere

**Comment by bkmgit** [comment]
Adding Turkana translations

**Comment by bkmgit** [comment]
@perepujal I think ok to submit as fuzzy

**Comment by bkmgit** [comment]
@perepujal Any update on this?

**Comment by h01ger** [comment]
hi, sorry for the long lack of responsse. can you please identify the commits related
to sw.po and tuv.po ?!?

**Comment by bkmgit** [comment]
Would separate sets of commits for tuv and sw be preferred? Can put
others into minor commits, each with separate pull requests, but unclear
if that is what is wanted.

**Comment by h01ger** [comment]
On Mon, Nov 13, 2023 at 05:28:52AM -0800, Benson Muite wrote:
> Would separate sets of commits for tuv and sw be preferred? 

yes, please.

> Can put
> others into minor commits, each with separate pull requests, but unclear
> if that is what is wanted.

seperate pull requests are not needed, but not harmful neither.

thank you!


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

We need to learn to live with cholera. What is the alternative? Breaking up
all streets, building drainage with toilets in every building? ***@***.***_)

**Comment by bkmgit** [comment]
Created separate pull requests for Kiswahili, Turkana and Estonian:
- https://github.com/tux4kids/tuxtype/pull/33
- https://github.com/tux4kids/tuxtype/pull/34
- https://github.com/tux4kids/tuxtype/pull/35

**Comment by h01ger** [comment]
On Mon, Nov 13, 2023 at 08:10:51AM -0800, Benson Muite wrote:
> Created separate pull requests for Kiswahili, Turkana and Estonian:
> - https://github.com/tux4kids/tuxtype/pull/33
> - https://github.com/tux4kids/tuxtype/pull/34
> - https://github.com/tux4kids/tuxtype/pull/35

thank you! also for closing this one!


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

Make facts great again.

**Pull request closed without merging**
